-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- DROP view public.user_private;
--
-- CREATE OR REPLACE VIEW "public"."user_private" AS
--  SELECT u.* FROM public.user u;
