import type {NextPage} from 'next'
import Head from 'next/head'
import {ComponentWithAlerts} from "../types/alerts";
import {alert} from "../utils/alert";
import React from "react";
import {useCurrentUser} from "../hooks/useCurrentUser";
import {serverSideTranslations} from "next-i18next/serverSideTranslations";
import {useTranslation} from "next-i18next";

const Home: NextPage<ComponentWithAlerts> = () => {
  const {user, error, fetching} = useCurrentUser();
  const {t} = useTranslation('common')

  const notify = () => {
    alert('INFO', 'Hello World !', 'This is a toast !')
  }



  return (
    <div className={''}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      <h1>{t('hello')}</h1>

      <button onClick={notify}>Make me a toast</button>
      <br/>
      <p>Error {JSON.stringify(error)}</p>
      <p>Fetching {JSON.stringify(fetching)}</p>
      <p>User {JSON.stringify(user)}</p>

          {/*Signed in as {session.user?.email} <br/>*/}
          {/*<button onClick={() => signOut()}>Sign out</button>*/}

      {/*{!session && <>*/}
      {/*    Not signed in <br/>*/}
      {/*    <button onClick={() => signIn()}>Sign in</button>*/}
      {/*</>}*/}


    </div>
  )
}

export async function getStaticProps({locale}: {locale: string}) {
  return {
    props: {
      ...(await serverSideTranslations(locale, ['common']))
    }
  }
}

export default Home
